Default: &defaults
  database: FirstTest.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: FirstTest_test.sqlite3
  <<: *defaults

Staging:
  database: FirstTest_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: FirstTest_production.sqlite3
  poolsize: 100
  <<: *defaults
